"""
Dasa Period Interpretations
============================
Ported from Library/Data/EventDataListStatic.cs (PD1 / PD2 / PD3 entries).

PD1  –  108 entries keyed by "<Sign><Planet>"
            Interpretation depends on the natal sign of the maha-dasa lord.
PD2  –  81 entries keyed by "<MahaLord><BhuktiLord>"
            Sub-period (antardasa) interpretation within a maha dasa.
PD3  –  81 entries keyed by "<MahaLord><AntarLord>"
            Pratyantardasa entries (all descriptions are empty in the source;
            only the nature / scores are preserved).

Each dict value has the shape:
{
    "name":        str,          # original C# EventName, e.g. "AriesSunPD1"
    "nature":      str,          # "Good" | "Bad" | "Neutral" | "Empty"
    "scores": {
        "mind":    str,
        "studies": str,
        "family":  str,
        "money":   str,
        "love":    str,
        "body":    str,
    },
    "description": str,
    "level":       str,          # "PD1" | "PD2" | "PD3"
}
"""

from typing import Dict, Optional

# ---------------------------------------------------------------------------
# PD1 – 108 entries  (12 signs × 9 planets)
# Key: "<Sign><Planet>"  e.g. "AriesSun", "CancerMoon"
# ---------------------------------------------------------------------------

PD1_DATA: Dict[str, dict] = {
    "AriesSun": {"name": "AriesSunPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Good", "love": "Good", "body": "Neutral"}, "description": "The Dasa of the Sun in Aries in deep exaltation.- Sudden gains in cattle and wealth, much traveling in eastern countries, residence in foreign countries, quarrels among friends and relations, pleasure trips and picnic parties and company of beautiful women.", "level": "PD1"},
    "TaurusSun": {"name": "TaurusSunPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Taurus - Increase in landed properties, fame among relations and friends, cultivation of love and reverence for holy people and saints.", "level": "PD1"},
    "GeminiSun": {"name": "GeminiSunPD1", "nature": "Good", "scores": {"mind": "Good", "studies": "Good", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Gemini - Much wealth, education, inclination to interest oneself in music and such other fine arts, and generally happy and cheerful.", "level": "PD1"},
    "CancerSun": {"name": "CancerSunPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Cancer - Political success, always gay and happy, traveling in foreign countries and increase in lands, houses and wealth.", "level": "PD1"},
    "LeoSun": {"name": "LeoSunPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Leo - Respect from kings and noble personages, righteous conduct, birth of children and respect among children.", "level": "PD1"},
    "VirgoSun": {"name": "VirgoSunPD1", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Virgo - Suffering off and on from physical complaints, loss of cattle, wealth and house and misunderstandings with close relatives and friends.", "level": "PD1"},
    "LibraSun": {"name": "LibraSunPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Libra - Reduced to poverty, troubled by enemies, failure in undertakings, death of brothers and friends and miserable and complicated life.", "level": "PD1"},
    "ScorpioSun": {"name": "ScorpioSunPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Scorpio - Starting new schemes and enterprises, realization of many ambitious things, travelling in hilly tracts and countries.", "level": "PD1"},
    "SagittariusSun": {"name": "SagittariusSunPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Sagittarius - Happiness, success in undertakings, good health, destruction of enemies, satisfaction in every way.", "level": "PD1"},
    "CapricornSun": {"name": "CapricornSunPD1", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Capricorn - A wandering life, loss of patrimony, self-respect and good name, misunderstanding among his own people.", "level": "PD1"},
    "AquariusSun": {"name": "AquariusSunPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Bad", "body": "Neutral"}, "description": "Aquarius - Mental worries, loss or illness to wife, loss of property and wealth.", "level": "PD1"},
    "PiscesSun": {"name": "PiscesSunPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Pisces - Gains in wealth, auspicious celebrations, respect among relations, increase in family members and smooth sailing in every way.", "level": "PD1"},

    "AriesMoon": {"name": "AriesMoonPD1", "nature": "Good", "scores": {"mind": "Good", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Good", "body": "Neutral"}, "description": "The Moon in Aries - Physical and mental happiness, gains in wealth and perfect contentment.", "level": "PD1"},
    "TaurusMoon": {"name": "TaurusMoonPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Taurus - Increase in fame and name, collection of enormous wealth, mental and physical happiness.", "level": "PD1"},
    "GeminiMoon": {"name": "GeminiMoonPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Gemini - Progress in education and acquiring of much immovable and movable properties.", "level": "PD1"},
    "CancerMoon": {"name": "CancerMoonPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Cancer - Addition in wealth, success in litigation, unexpected findings of treasure, travels.", "level": "PD1"},
    "LeoMoon": {"name": "LeoMoonPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Leo - Progress in education, much gains from unexpected sources.", "level": "PD1"},
    "VirgoMoon": {"name": "VirgoMoonPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Neutral", "body": "Bad"}, "description": "Virgo - Death of serious illness to mother, worries from enemies and swindlers, mental and physical restlessness.", "level": "PD1"},
    "LibraMoon": {"name": "LibraMoonPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Libra - Gains in wealth, increase in friends, visits to holy places and shrines, realisation of schemes and destruction of enemies.", "level": "PD1"},
    "ScorpioMoon": {"name": "ScorpioMoonPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Scorpio - Fear from political heads, destruction of relatives, disappointments in every respect, loss of wealth, liberty and honor at risk and much mental uneasiness.", "level": "PD1"},
    "SagittariusMoon": {"name": "SagittariusMoonPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Sagittarius - Domestic happiness and felicity, celebration of happy functions, accumulation of wealth and undisturbed progress of normal private affairs.", "level": "PD1"},
    "CapricornMoon": {"name": "CapricornMoonPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Capricorn - Increase in lands and houses and wealth, success in every new enterprise, pilgrimages to holy places and success in litigation.", "level": "PD1"},
    "AquariusMoon": {"name": "AquariusMoonPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Aquarius - Destruction of property, fear from political authorities, mental worries from enemies, misunderstandings among relatives and friends.", "level": "PD1"},
    "PiscesMoon": {"name": "PiscesMoonPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Pisces - Taking charges of fresh office, reciting religious texts and moral codes and easy access to anything coveted without effort.", "level": "PD1"},

    "AriesMars": {"name": "AriesMarsPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Aries - Acquisition of wealth, increase in reputation and respect, much gain.", "level": "PD1"},
    "TaurusMars": {"name": "TaurusMarsPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Taurus - Destruction of enemies, success in all struggles, respect from elders and rulers and good produce from lands.", "level": "PD1"},
    "GeminiMars": {"name": "GeminiMarsPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Gemini - Access to great wealth, precious stones and agricultural success, general success in all undertakings.", "level": "PD1"},
    "CancerMars": {"name": "CancerMarsPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Neutral", "body": "Bad"}, "description": "Cancer - Danger from enemies, of honour and reputation, domestic disharmony and misunderstandings among brothers or close relatives.", "level": "PD1"},
    "LeoMars": {"name": "LeoMarsPD1", "nature": "Good", "scores": {"mind": "Good", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Leo - Happy and successful all through the period of 7 years, taste in fine arts and material gains through them, increase of income from house and lands.", "level": "PD1"},
    "VirgoMars": {"name": "VirgoMarsPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Good", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Virgo - Beneficial results, successful termination of educational pursuits, ability to address meetings and deliver lectures, and happiness from relatives and friends.", "level": "PD1"},
    "LibraMars": {"name": "LibraMarsPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Libra - Most miserable life, misunderstandings with cousins and brothers, death of wife and children, loss of wealth and grains and mortgaging of landed property.", "level": "PD1"},
    "ScorpioMars": {"name": "ScorpioMarsPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Good", "body": "Neutral"}, "description": "Scorpio - Increase in wealth, good earnings, friendship and intimacy with exalted personages, love for own people, always happy and active.", "level": "PD1"},
    "SagittariusMars": {"name": "SagittariusMarsPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Sagittarius - Earnings from political or royal sources, courting their friendships, destruction of enemies and realisation of all hopes and desires.", "level": "PD1"},
    "CapricornMars": {"name": "CapricornMarsPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Capricorn - Success in battles and respect for military skill, gains from quadrupeds and increase in wealth.", "level": "PD1"},
    "AquariusMars": {"name": "AquariusMarsPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Aquarius - Great hardships and difficulties, misunderstandings with rulers and the immediate superiors in office, unpleasant relations with mother and servants.", "level": "PD1"},
    "PiscesMars": {"name": "PiscesMarsPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Pisces - Much wealth, general success and happiness. bumper crops in lands, prosperity and acquisition of house and business, respect as a learned man, great reputation.", "level": "PD1"},

    "AriesRahu": {"name": "AriesRahuPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Rahu In Aries - Auspicious celebrations in the house, recitations of sacred texts, acquisition of tracts of land, perfect domestic happiness, respect from rulers and a life of harmony in every respect.", "level": "PD1"},
    "TaurusRahu": {"name": "TaurusRahuPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Taurus - Pilgrimages to shrines and holy places, increase in philosophical knowledge, entertainments, gains from cattle and dealings with quadrupeds.", "level": "PD1"},
    "GeminiRahu": {"name": "GeminiRahuPD1", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Bad", "body": "Neutral"}, "description": "Gemini - Multiplication of enemies, always peevish and short tempered, fear from police and magistrates, sickness to wife and family, misunderstandings and disfavour.", "level": "PD1"},
    "CancerRahu": {"name": "CancerRahuPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Cancer - Serving the suffering, humanitarian propaganda, zeal and enthusiasm for national service, gains and increase in wealth, riches and honour and great reputation.", "level": "PD1"},
    "LeoRahu": {"name": "LeoRahuPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Neutral", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Leo - Fear of imprisonment of fraud and deception or misappropriation or political offenses, destruction of property and mental worries distractions.", "level": "PD1"},
    "VirgoRahu": {"name": "VirgoRahuPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Virgo - Gain in wealth, general prosperity and success, acquisition of new lands, elevation to exalted positions, respect for learning, sexual happiness and domestic harmony, birth of children and sudden access to much wealth.", "level": "PD1"},
    "LibraRahu": {"name": "LibraRahuPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Libra - Destruction of property, loss of wealth, waste of agricultural products, loss of position, fear of imprisonment, residence in foreign countries-rather in exile, many miseries, hardships, business failure, litigation troubles and physical and mental sufferings.", "level": "PD1"},
    "ScorpioRahu": {"name": "ScorpioRahuPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Scorpio - Rahu is debilitated here and as such, causes great havoc to the native. The results in Rahu's Dasa will be: abortion, loss of children, inclination to bid farewell to moral aspect of life, failure in business enterprises and mental discontentment.", "level": "PD1"},
    "SagittariusRahu": {"name": "SagittariusRahuPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Sagittarius - Acquisition of wealth, sudden and unexpected gain without effort, great success in any undertakings, loss of near and dear relatives and mental unrest.", "level": "PD1"},
    "CapricornRahu": {"name": "CapricornRahuPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Capricorn - Sudden promotions to higher positions, recognition of one's merits by the State and rulers, marriage festivities at home, increase of wealth and general prosperity.", "level": "PD1"},
    "AquariusRahu": {"name": "AquariusRahuPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Bad", "body": "Neutral"}, "description": "Aquarius - Orphanage, disappointments, mental derangement and affection, sorrowful news, loss of wife or children, premature death and mean instincts.", "level": "PD1"},
    "PiscesRahu": {"name": "PiscesRahuPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Pisces - Great fear in life from thieves, swindlers and such people, inclination to matrimonial alliance, progress of education, some gains, ill health and mental uneasiness. Rahu in Pisces gives mixed results - his position, viz., whether he is in a friendly or unfriendly sign, in the house of loss or gain, wife or children, etc., should be correctly determined.", "level": "PD1"},

    "AriesJupiter": {"name": "AriesJupiterPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Jupiter in Aries - Acquisition of landed property, general prosperity and success in all undertakings and litigations, elevation to a responsible office or appointment as a trustee and great respect from his or her own people.", "level": "PD1"},
    "TaurusJupiter": {"name": "TaurusJupiterPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Taurus - If a king or a president - access to new territories, fresh treaties and pacts, if an ordinary person - acquisition of wealth, establishment of business on a firm foundation, gains in trade and agriculture, increase in lands and cattle, respect from friends and foes.", "level": "PD1"},
    "GeminiJupiter": {"name": "GeminiJupiterPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Bad", "body": "Neutral"}, "description": "Gemini - Death of wife if married or sweet heart, loss of children, brothers and cousins, deportation, fear from rulers and mental uneasiness.", "level": "PD1"},
    "CancerJupiter": {"name": "CancerJupiterPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Cancer - Jupiter is exalted here and gives all beneficial results such as much political success, promotions, exalted positions, humanitarian work, national service, acquisition of wealth from unexpected sources and without efforts, journalistic success, minister of education or lands and perfect harmony in domestic life.", "level": "PD1"},
    "LeoJupiter": {"name": "LeoJupiterPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Leo - Respect from rulers, gain of lands, much agricultural produce, and realisation of one's own desires and ambitions.", "level": "PD1"},
    "VirgoJupiter": {"name": "VirgoJupiterPD1", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Bad", "body": "Bad"}, "description": "Virgo - Residence in foreign countries, destruction of wife and property, loss of wealth, misunderstandings among relatives, strife, body ill-health and symptoms of nervous troubles and diseases.", "level": "PD1"},
    "LibraJupiter": {"name": "LibraJupiterPD1", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Libra - Residence in desolate places, dissolute and shameful life, active part in perverted social reform, selfish interests, great and unbearable difficulties and troubles, tendency to create factions in societies and families.", "level": "PD1"},
    "ScorpioJupiter": {"name": "ScorpioJupiterPD1", "nature": "Good", "scores": {"mind": "Good", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Scorpio - Mental calm and happiness, acquisition of new lands and estates, undisturbed progress and religious worship and philosophical discourses and triumph of spiritual influences over sensual passions, reputation at stake if aspected by malefics.", "level": "PD1"},
    "SagittariusJupiter": {"name": "SagittariusJupiterPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Sagittarius - Many sons, much wealth, success in every undertaking, increase in relations and family members. widespread fame and perfect happiness.", "level": "PD1"},
    "CapricornJupiter": {"name": "CapricornJupiterPD1", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Capricorn - Death or illness of children, wife always ill, loss of property, reputation and self-respect, irreligious acts, sacrilegious attacks upon sacred institutions, predominance of mean motives, liable to prosecution and the upspringing of numerous enemies.", "level": "PD1"},
    "AquariusJupiter": {"name": "AquariusJupiterPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Aquarius - Consumption and fear from wild beasts, animals, bad luck, many hardships and loss of wealth.", "level": "PD1"},
    "PiscesJupiter": {"name": "PiscesJupiterPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Pisces - Much fame throughout this long period of 16 years, high education and gain from exhibition of knowledge, acquisition of property and general success and happiness.", "level": "PD1"},

    "AriesSaturn": {"name": "AriesSaturnPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Saturn In Aries - The worst period in a man's career, unexpected losses, disappointments in every undertaking, misunderstandings among relatives and friends and increase in the number of enemies.", "level": "PD1"},
    "TaurusSaturn": {"name": "TaurusSaturnPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Taurus - Success and gains in agricultural operations, much prosperity to the cattle and other domestic animals, great income, and access to things desired.", "level": "PD1"},
    "GeminiSaturn": {"name": "GeminiSaturnPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Gemini - Recognition of his services, great humanitarian work, profits in speculations and trade, respect from rulers, political success, reputation, fame and much general happiness.", "level": "PD1"},
    "CancerSaturn": {"name": "CancerSaturnPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Neutral", "body": "Bad"}, "description": "Cancer - Miseries and calamities, family strife, increase of enemies, trouble from relatives and physical diseases and mental affliction.", "level": "PD1"},
    "LeoSaturn": {"name": "LeoSaturnPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Bad", "body": "Neutral"}, "description": "Leo - A period of uneasiness, distrust, disappointments and unrest, misappropriation of money and consequent prosecution if Saturn is afflicted powerfully, hatred by all and courting death as a source of relief from mental worries.", "level": "PD1"},
    "VirgoSaturn": {"name": "VirgoSaturnPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Virgo - Elevation to exalted positions, royal favour, business success and establishment of fame and reputation.", "level": "PD1"},
    "LibraSaturn": {"name": "LibraSaturnPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Libra - Travelling in countries inhabited by Christians and Moslems, establishment of fresh branches if proprietor of a business concern, acceptance of invitations for public lectures and great honour and respect throughout the long period of 19 years and perfect domestic happiness.", "level": "PD1"},
    "ScorpioSaturn": {"name": "ScorpioSaturnPD1", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Scorpio - Odium of superiors, disliked and hated by all, loss or prestige, self-respect and fame and destruction and damage to property and possessions.", "level": "PD1"},
    "SagittariusSaturn": {"name": "SagittariusSaturnPD1", "nature": "Good", "scores": {"mind": "Good", "studies": "Good", "family": "Good", "money": "Neutral", "love": "Good", "body": "Neutral"}, "description": "Sagittarius - Inclination to study philosophical and religious treatises and success in such studies, auspicious occasions like marriage ceremonies, etc., at home and happiness and mental peace throughout.", "level": "PD1"},
    "CapricornSaturn": {"name": "CapricornSaturnPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Capricorn - Increase in lands, gains in wealth and business, friendship with great and illustrious personages.", "level": "PD1"},
    "AquariusSaturn": {"name": "AquariusSaturnPD1", "nature": "Good", "scores": {"mind": "Good", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Aquarius - Great travelling in Western countries, success in litigation, mental happiness and acquisition of wealth.", "level": "PD1"},
    "PiscesSaturn": {"name": "PiscesSaturnPD1", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Pisces - Pilgrimage to sacred shrines and holy places, indifference towards sectarian restrictions and observances, sorrows, misery and unrest.", "level": "PD1"},

    "AriesMercury": {"name": "AriesMercuryPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Mercury in Aries - Marriage, performance of religious and social work, charity, increase in religiousness and intelligence, favour of rulers, gains from cultivation. cattle, precious stones and conveyances and happiness through these.", "level": "PD1"},
    "TaurusMercury": {"name": "TaurusMercuryPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Good", "body": "Good"}, "description": "Taurus - Great happiness, sexual contact with beautiful young women, getting titles and name, ornaments and authority over men, acquaintance of sweet girls and their company and practice of music and kindred sciences.", "level": "PD1"},
    "GeminiMercury": {"name": "GeminiMercuryPD1", "nature": "Good", "scores": {"mind": "Good", "studies": "Good", "family": "Good", "money": "Good", "love": "Good", "body": "Neutral"}, "description": "Gemini - Access to great intellectual treasures, increase in knowledge, successful termination of educational career, acquisition of fame and wealth, happiness from wife and children, marriage ceremonies and recitation of sacred scriptures.", "level": "PD1"},
    "CancerMercury": {"name": "CancerMercuryPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Cancer - Degradation, change of residence, fines and imprisonments, penalties. confinement in chains, hatred of relations, loss of lands. failure of crops and comity with all.", "level": "PD1"},
    "LeoMercury": {"name": "LeoMercuryPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Leo - Good courage and elevation, travelling in hilly and mountainous tracts, acquisition of wealth from various countries, progress in knowledge, expeditions to mountains, caves and similar places, marriage and great reputation.", "level": "PD1"},
    "VirgoMercury": {"name": "VirgoMercuryPD1", "nature": "Good", "scores": {"mind": "Good", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Good", "body": "Good"}, "description": "Virgo - The most auspicious and happy period of life, favour of kings, admirers and royal courts and great success in them, undisturbed health, marriage in the house, increase in intelligence, religiousness, charitable foundings, and unexpected gains.", "level": "PD1"},
    "LibraMercury": {"name": "LibraMercuryPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Libra - Great works published in the native's name, favour of wealthy and educated people without effort, and leadership over men.", "level": "PD1"},
    "ScorpioMercury": {"name": "ScorpioMercuryPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Bad", "body": "Neutral"}, "description": "Scorpio - Loss or wife, children, riches, mental troubles, losses from merchandise, great hatred of people and relations and loss of reputation and power.", "level": "PD1"},
    "SagittariusMercury": {"name": "SagittariusMercuryPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Neutral", "money": "Neutral", "love": "Good", "body": "Neutral"}, "description": "Sagittarius - Success in education, meeting with learned and religious people, worship of holy men, virtuous and charitable deeds, travelling in Eastern countries, inclination for marital enterprises and great exhilaration.", "level": "PD1"},
    "CapricornMercury": {"name": "CapricornMercuryPD1", "nature": "Good", "scores": {"mind": "Good", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Capricorn - Success in trade, inception of new business-like trades in tanneries, leather goods, glassware, etc., recitation of religious scriptures. Godly contemplations, patronage of kings, destruction of foes and enemies and general success in life.", "level": "PD1"},
    "AquariusMercury": {"name": "AquariusMercuryPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Aquarius - Acquisition of paraphernalia, access to good and much wealth, indulging in a pleasurely life and good fame and name.", "level": "PD1"},
    "PiscesMercury": {"name": "PiscesMercuryPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Pisces - Trouble from thieves, dysentery, destruction of relations, litigation, quarrels with relatives, mental derangement, nervous breakdown and failure in attempts.", "level": "PD1"},

    "AriesKetu": {"name": "AriesKetuPD1", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Bad", "body": "Neutral"}, "description": "Ketu in Aries - Disgrace, troubles from relatives, loss of property, cattle and other domestic animals, constant travels in Eastern countries, great hardship, sudden quarrels, loss of mother and wife or their serious sickness, want of prudence and capacity in private matters.", "level": "PD1"},
    "TaurusKetu": {"name": "TaurusKetuPD1", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Taurus - Many dangers, death of wife, acquisition of wealth through evil ways and means, sexual sorrows, visits to sacred shrines and holy waters, inclination to religious study and success in it, compunction and in the end appeasing sins by resort to foul stratagems.", "level": "PD1"},
    "GeminiKetu": {"name": "GeminiKetuPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Bad", "body": "Neutral"}, "description": "Gemini - Good health, happiness, elevation to responsible and exalted positions, rounding of sacred institutions, good food, advent of relations and in later years venereal troubles, death of near relation and loss of reputation and self-respect.", "level": "PD1"},
    "CancerKetu": {"name": "CancerKetuPD1", "nature": "Good", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Neutral", "body": "Bad"}, "description": "Cancer - Many dangers, disturbances from his place and a period of exile, serious sickness to wife, parents or children, and if badly afflicted, their death, quarrels with friends, initiation into the mysteries of philosophical knowledge.", "level": "PD1"},
    "LeoKetu": {"name": "LeoKetuPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Neutral", "money": "Neutral", "love": "Good", "body": "Neutral"}, "description": "Leo - Increase of lands, cultivation. progress in education, heated debates and discussions on philosophical and scientific subjects with great scholars and eminent people, attracted by females and company with them, travels in mountainous tracts and hilly countries to spread any righteous cause, and treated to great musical entertainment.", "level": "PD1"},
    "VirgoKetu": {"name": "VirgoKetuPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Bad", "body": "Bad"}, "description": "Virgo - Fear from fires, weapons and poisonous gases, beasts and reptiles, destruction of dear lives, properties and self-respect, unrighteous acts and nasty venereal complaints.", "level": "PD1"},
    "LibraKetu": {"name": "LibraKetuPD1", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Bad"}, "description": "Libra - Happiness and prosperity to wife or husband, self and children, enmity of relations, gains from gold and precious stones, headache, heart disease, nervous breakdown, trouble in the anus and much discontent.", "level": "PD1"},
    "ScorpioKetu": {"name": "ScorpioKetuPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Good", "love": "Bad", "body": "Bad"}, "description": "Scorpio - Living dependent on relations, sycophant acts, acquisition of much wealth. loss of few children, gains from lands, contraction of new friendship from among the members of the fair sex and liable to suffer from venereal complaints.", "level": "PD1"},
    "SagittariusKetu": {"name": "SagittariusKetuPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Good", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Sagittarius - Perfect domestic harmony and happiness, favour from aristocrats, progress in education, religious discussions, moral elevation and manifestation of a spirit of tolerance and equality.", "level": "PD1"},
    "CapricornKetu": {"name": "CapricornKetuPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Capricorn - Misappropriation of private and governmental funds and consequent prosecution, wife or husband catching consumption and such diseases, death of a few children, anxiety about everything, misunderstanding with relations and disgrace and disappointments.", "level": "PD1"},
    "AquariusKetu": {"name": "AquariusKetuPD1", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Aquarius - Hating all and hated by all, incurring the displeasure of superiors, pessimistic about every hope, abject dependency and servile flattery; in the end, happiness and prosperity to wife and children.", "level": "PD1"},
    "PiscesKetu": {"name": "PiscesKetuPD1", "nature": "Good", "scores": {"mind": "Good", "studies": "Good", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Pisces - Learned discussions, general success, helping the suffering, mental depression, promotion, acquisition of fertile lands, favour of the superiors and moneyed people, moral and religious devotions, vigorous and clear understanding, travel on water to distant countries and respect there.", "level": "PD1"},

    "AriesVenus": {"name": "AriesVenusPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Good", "body": "Neutral"}, "description": "Venus in Aries - Residence in palatial buildings, acquaintance with noble personages, wearing good clothes, good earnings, spread of fame, much respect, birth of child, happy sexual relations and praised by friends and enemies.", "level": "PD1"},
    "TaurusVenus": {"name": "TaurusVenusPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Good", "body": "Neutral"}, "description": "Taurus - A life of great ease and indulgence throughout the period of 20 years, enjoyment of much happiness, company of beautiful girls and joy through association with them, travels on seas to foreign countries particularly southern, all ambitions of life fairly realised, redemption from debts, symptoms of venereal troubles.", "level": "PD1"},
    "GeminiVenus": {"name": "GeminiVenusPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Gemini - Gain of territory, affording protection to brothers, sisters, cousins and paternal uncles and aunts, gain of vehicles, increase of reputation, children. harmony with wife, mental peace and a check over inclination to indulge in loose life.", "level": "PD1"},
    "CancerVenus": {"name": "CancerVenusPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Cancer - Paroxysms of grief and terror, destruction of property, discontent with relations, increase of enemies, loss of wealth, disturbance to good work and some mental ease in the end.", "level": "PD1"},
    "LeoVenus": {"name": "LeoVenusPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Bad", "body": "Bad"}, "description": "Leo - Mental disease and sorrow, troubles from fires, poisons and hurts, evil women, foul language and mental disorder, exile, and aimless wanderings in deserts and woods to evade detection by law, dangerous sickness to the better half or a child, stigma on self-respect due to mean fellows and inclination to conceal true identity.", "level": "PD1"},
    "VirgoVenus": {"name": "VirgoVenusPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Bad", "body": "Bad"}, "description": "Virgo - Quarrels with wife or husband and separation from him or her, mortgage of all property, trouble in the generative organ often leading to surgical operation, symptoms of arthritis, troubles relating to nervous breakdown, mental unrest, separation from relatives and friends and much grief and sorrow.", "level": "PD1"},
    "LibraVenus": {"name": "LibraVenusPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Libra - Great reputation, gain of wealth from royal patronage, comforts, good enjoyment of life, luxurious invitations and worships of mammon and a period of extreme sensuality.", "level": "PD1"},
    "ScorpioVenus": {"name": "ScorpioVenusPD1", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Scorpio - Hatred for all, many miseries and troubles, serious risks, vengeance against relatives, loss of wealth and property, mental affliction and imbalance.", "level": "PD1"},
    "SagittariusVenus": {"name": "SagittariusVenusPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Sagittarius - Much fame and name, religious and philosophical studies, recitation of sacred writings, regard for holy people and ascetics, success in any undertakings and general prosperity.", "level": "PD1"},
    "CapricornVenus": {"name": "CapricornVenusPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Capricorn - Travels in foreign lands, freedom from domestic worries, discussion with learned people, progress in general education, acquaintance with low class people, development of perverted ideas of social or religious reform and success in all endeavors.", "level": "PD1"},
    "AquariusVenus": {"name": "AquariusVenusPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Aquarius - Acquisition of fresh property, a good library, lands and houses, honours and unexpected gains, love for Christian or Islamic literature and its studies, stray intercourse with senile women, domestic happiness and harmony.", "level": "PD1"},
    "PiscesVenus": {"name": "PiscesVenusPD1", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Pisces - High political power and great success, promotion to responsible office, acts of charity and generosity, exercise of prudence in official matters and perfect happiness in domestic life and smooth-sailing in every respect.", "level": "PD1"},
}

# ---------------------------------------------------------------------------
# PD2 – 81 entries  (9 maha lords × 9 bhukti lords)
# Key: "<MahaLord><BhuktiLord>"  e.g. "SunMoon", "JupiterSaturn"
# ---------------------------------------------------------------------------

PD2_DATA: Dict[str, dict] = {
    "SunSun": {"name": "SunSunPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Unpleasantness with relatives and superiors, anxieties, headache, pain in the ear, some tendency to urinary or kidney troubles, sickness, fear from rulers and enemies, fear of death, loss of money, danger to father if the Sun is afflicted, stomachache and travels, gains through religious people, mental sufferings, a wandering life in a foreign country.", "level": "PD2"},
    "SunMoon": {"name": "SunMoonPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "The Moon's sub-period-6 months Winning favour from superiors, increase in business, fresh enterprises, troubles through women, eye troubles, many relatives and friends, indulgence in idle pastimes, jaundice and kindred ailments, new clothes and ornaments, will be happy, healthy, good meals, respect among relatives.", "level": "PD2"},
    "SunMars": {"name": "SunMarsPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Mars' sub-period-4 months, 6 days. Rheumatic and similar troubles, quarrels, danger of enteric fever, dysentery, troubles to relatives, loss of money by thefts or wasteful expenses, failures, acquisition of wealth in the form of gold and gems, royal favour leading to prosperity, contraction and transmission of bilious and other diseases, mental worries, danger from fire, ill-health, loss of reputation, sorrow.", "level": "PD2"},
    "SunRahu": {"name": "SunRahuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Rahu's sub-period - 10 months, 24 days. Many troubles, changes according to the position of Rahu, family disputes, journeys, fear of death, trouble from relatives and enemies, loss of peace or mental misery, loss of money, sorrows, unsuccessful in all attempts, fear of thieves and reptiles, scandals.", "level": "PD2"},
    "SunJupiter": {"name": "SunJupiterPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Jupiter's sub-period-9 months, 18 days. Benefits from friends and acquaintances, increase in education, employment in high circles, association with people of high rank, success through obstacles, birth of a child, wealth got through sons (if there is a son), honour to religious people, virtuous acts, good traditional observances, good society and conversations, reputation, gains and court-honours.", "level": "PD2"},
    "SunSaturn": {"name": "SunSaturnPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Saturn's sub-period--11 months, 12 days. Constant sickness to family members, new enemies, some loss of property, bodily ailment, much unhappiness, displacement from home accidents, quarrels with relatives, loss of money, disease, lacking in energy, ignoble calls, mental worries, loans, danger from thieves and rulers.", "level": "PD2"},
    "SunMercury": {"name": "SunMercuryPD2", "nature": "Neutral", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Mercury's sub-period-10 months, 6 days. Gain in money, good reputation, acquisition of new clothes and ornaments, new education, trouble through relatives, mental distress, depression of spirits, waste of money and nervous weakness, no comforts, friends becoming enemies, much anxiety and fears, health bad, children ungrateful, disputes and trouble from ruler or judge, suffer disgrace, many short journeys and wanderings.", "level": "PD2"},
    "SunKetu": {"name": "SunKetuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Ketu's sub-period - 4 months, 6 days. Loss of money, affliction of mind with troubles, fainting or nervous exhaustion, mind full of misgivings, a long journey to a distant place, change of house due to disputes, troubles among relatives and associates, throat disease, mental anguish, ophthalmia, serious illness, fear from kings or rulers and enemies, diseases, cheated by others.", "level": "PD2"},
    "SunVenus": {"name": "SunVenusPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Venus sub-period - 1 year. Gain of money, respect by rulers and gain of vehicles, likelihood of marriage, increase of property, illness, does many good works, acquisition of pearls or other precious stones, fatigue, addiction to immoral females and profitless discussions.", "level": "PD2"},

    "MoonSun": {"name": "MoonSunPD2", "nature": "Neutral", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Bad"}, "description": "The Sun's sub-period - 6 months. Feverish complaints, pains in the eyes, success or failure according to position of the Sun and the Moon, legal power, free from diseases, decadence of enemies, happiness and prosperity, jaundice, dropsy, fever, loss of money, travels, danger to father and mother, piles, weakness, loss of children and friends.", "level": "PD2"},
    "MoonMoon": {"name": "MoonMoonPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "The Moon's sub-period- 10 months. Devoted attention to learning, love or music, good clothing, company of refined society, sound health, good reputation, journey to holy places, acquisition of abandoned wealth, power, vehicles and lands; marriage, relatives, fortunate deeds, inclination to public life, change of residence, birth of a child, increase of wealth, prosperity to relatives.", "level": "PD2"},
    "MoonMars": {"name": "MoonMarsPD2", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Mars's sub-period - 7 months. Quarrels and litigation among friends and relatives, headlong enterprises, danger of disputes between husband and wife, between lovers or in regard to marital affairs; disease, petulence, loss of money, waste of wealth, trouble from brothers and friends, danger from fever and fire, injury from instruments or stones, loss of blood and disease to household animals.", "level": "PD2"},
    "MoonRahu": {"name": "MoonRahuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Rahu's sub-period - 1 year, 6 months. Distress of risks from falls and dangerous diseases, waste of wealth and loss of relatives and no ease to body, loss of money, danger of stirring up enemies, sickness, anxiety, enmity of superiors and elders, anxiety and troubles through wife, scandals, change of residence, diseases of skin, danger from thieves and poison, ill-health to father and mother, suffering from hunger.", "level": "PD2"},
    "MoonJupiter": {"name": "MoonJupiterPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Jupiter's sub-period - 1 year, 4 months. Increase of property, plenty of food and comforts, prosperous, benefits from superiors such as masters or governors, birth of a child, vehicles, abundance of clothes and ornaments and success in undertakings, patronage or rulers, gain or property, respect, learned.", "level": "PD2"},
    "MoonSaturn": {"name": "MoonSaturnPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Saturn's sub-period - 1 year, 7 months. Wife's death or separation, much mental anguish, loss of property, loss of friends, ill health, mental trouble due to mother, wind and bilious affections, harsh words, and discussion with unfriendly people, disease due to indigestion, no peace of mind, quarrels with relatives.", "level": "PD2"},
    "MoonMercury": {"name": "MoonMercuryPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Good", "body": "Neutral"}, "description": "Mercury's sub-period - 1 year, 5 months. Acquisition of wealth from maternal relatives, new clothes and ornaments, settlement of disputes, pleasure through children or lover, increase of wealth, accomplishment of desires, intellectual achievements, new education, honour from rulers, general happiness, enjoyment with females, addiction to betting and drinks.", "level": "PD2"},
    "MoonKetu": {"name": "MoonKetuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Ketu's sub-period - 7 months. Illness to wife, loss of relatives, suffering from stomach ache, loss or property, sickness of a feverish nature, danger from fire, subject to swellings or eruptions, eye troubles, mind filled with cares, public criticism or displeasure, dishonor, danger to father, mother and children, scandals among equals, eating of prohibited food, bad acts, bad company, loss of money and memory.", "level": "PD2"},
    "MoonVenus": {"name": "MoonVenusPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Venus's sub-period - 1 year, 8 months. Sudden gain from wife, enjoys comforts of agriculture, water products and clothing, suffers from diseases inherited by mother, sickness, pain, loss of property, enmity, gain of houses, good works and good meals, birth of children, expenses due to marriage or other auspicious acts.", "level": "PD2"},

    "MarsSun": {"name": "MarsSunPD2", "nature": "Neutral", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "The Sun's sub-period - 4 months, 6 days. Gain of money in bad ways, destruction of enemies, good reputation, long journey to foreign lands and peace of mind, blame, odium of elders, quarrels with them, sufferings by diseases, heartache occasioned by one's own relatives, fever or other inflammatory affection, danger of fire, troubles through persons in position, many enemies.", "level": "PD2"},
    "MarsMoon": {"name": "MarsMoonPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Good", "body": "Neutral"}, "description": "The Moon's sub-period -7 months. Profit, acquisition of wealth, house renovated or some improvements effected in it, comforts of wealth, heavy sleep, ardent passion, enjoyment by the help or women.", "level": "PD2"},
    "MarsMars": {"name": "MarsMarsPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Mars's sub-period - 4 months, 27 days. Great heat, dislike of friends, annoyance from brothers and sisters, danger from rulers, failure of all undertakings, danger of hurts according to the sign held by Mars, trouble with superiors and some anxiety through strangers, foreigners or people abroad and through warlike clan. Danger of open violence, quarrel with relations, loss of money, skin disease, consumption, loss of blood, fistula, and fissures in anus, loss of females and brothers, evil doings and boils.", "level": "PD2"},
    "MarsRahu": {"name": "MarsRahuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Rahu's sub-period - 1 year, 18 days. Danger from rulers and robbers, loss of wealth, success in evil pursuits, suffering from poisonous complaints, loss of relatives, danger from skin diseases, change of residence, some severe kind of cutaneous disease, journey to a foreign country, scandals, loss of cows and buffaloes, illness to wife, loss of memory, fear from insects and thieves, falls into well, fear from ghosts, affection of gonorrhea, fretting and litigation.", "level": "PD2"},
    "MarsJupiter": {"name": "MarsJupiterPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Jupiter's sub-period - 11 months, 6 days. Loss of wealth, enemies, end the unfortunate period, favour from superiors and persons in position, gain of money, birth of children, auspicious celebrations, acquisition or wealth through holy people, freedom from illness, public reputation, ascendancy and happiness.", "level": "PD2"},
    "MarsSaturn": {"name": "MarsSaturnPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Saturn's sub-period - 1 year, 1 month, 9 days. Loss of money, diseases, loss of relatives and danger from arms or operation, illness leading to misery, evil threatened by enemies and robbers, disputes with rulers, loss of wealth, quarrel, disputes, litigation, loss of property, cutaneous effects. loss of office or position and much anxiety.", "level": "PD2"},
    "MarsMercury": {"name": "MarsMercuryPD2", "nature": "Neutral", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Mercury's sub-period- 11 months, 27 days. Marriage or inclination to marriage, knowledge and fruits of knowledge, wealth, bodily evils disappear, slander, fear of insects, poisoned by animals and insects, gain of wealth by trade, abundance of houses, trouble from enemies and mental worries, service rendered to friends and relatives, new knowledge, success in litigation.", "level": "PD2"},
    "MarsKetu": {"name": "MarsKetuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Ketu's sub-period - 4 months, 27 days. Enmity and quarrels with low people, loss of money due to evil works, commission of sins, great sufferings due to troubles from relatives and brothers and opposition of bad people, family disputes, troubles with one's own kindred diseases, poisonous complaints, trouble through women, many enemies.", "level": "PD2"},
    "MarsVenus": {"name": "MarsVenusPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Good", "body": "Bad"}, "description": "Venus's sub-period - 1 year, 2 months. Acquisition of property, gain of money, domestic happiness, successful love affairs, inclination towards religious observances and festivities, favourable associations, influenced by priests, skin eruptions, boils, pleasure from travelling, jewels to wife, clothing, money from relatives and brothers, odium of females and their society, increase of intelligence, enjoyment of females and gain of money.", "level": "PD2"},

    "RahuSun": {"name": "RahuSunPD2", "nature": "Neutral", "scores": {"mind": "Neutral", "studies": "Good", "family": "Bad", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "The Sun's sub-period - 10 months, 24 days. Hot fevers, giddiness, fear and enmity of people, quarrels in family, benefits from persons in good position, fear and suspicion in connection with wife, children and relatives, change of position or residence, love of charitable acts, contentment, cessation of all violence and outrage of contagious diseases, success in examinations, private life happy, much reputation and fame, but mental unrest.", "level": "PD2"},
    "RahuMoon": {"name": "RahuMoonPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Bad", "body": "Bad"}, "description": "Moon - 1 year, 6 months. Abundance of enjoyments, good crops, coming in of money and communion with kith and kin, loss of relatives, loss of money through wife, pains in the limbs, change of position or residence, danger of personal hurts, unstability of health, sea voyages, gain of lands and money, loss or danger to wife and children.", "level": "PD2"},
    "RahuMars": {"name": "RahuMarsPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Bad", "body": "Bad"}, "description": "Mars - 1 year, 18 days. Danger from rulers, fires or thieves and by arms, defeat in litigation, loss of money due to cousins, difficulties, sorrows, danger to the person due to malice of enemies, tendency to ease or dissolute habits, disputes and mental anxiety, combination of all possible calamities, bewilderment in every work and culpable failure of memory.", "level": "PD2"},
    "RahuRahu": {"name": "RahuRahuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Bad", "body": "Bad"}, "description": "Rahu - 2 years, 8 months, 12 days. Disturbance in mind, anxieties, quarrels among relatives, death of partner, master or the head of the family, mental anxiety, danger of poisoning, transfer, all sorts of scandals and quarrels, fever, bites of insects or wounds by arms, death of relatives, going to court as witness, quarrels with parents, diseases, illness to wife, failure of intellect, loss of wealth, wandering in far-off countries and distress there.", "level": "PD2"},
    "RahuJupiter": {"name": "RahuJupiterPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Jupiter - 2 years, 4 months, 24 days. Total disappearance of enemies and sickness, royal favour, acquisition of wealth, birth of children, increase of pleasure, gain through nobles or persons in power, benefits and comforts from superiors, success in all efforts, marriage in the house, increase of enemies, litigations and dips in sacred rivers.", "level": "PD2"},
    "RahuSaturn": {"name": "RahuSaturnPD2", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Bad", "body": "Bad"}, "description": "Saturn - 2 years, 10 months, 6 days. Scandal, danger due to fall of a tree, bad associations, divorce of wife or husband, incessant disputes and contests, rheumatism, biliousness, etc., throughout: disease due to wind and bile, distress of relatives, friends and well-wishers, residence in a remote foreign land.", "level": "PD2"},
    "RahuMercury": {"name": "RahuMercuryPD2", "nature": "Neutral", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Mercury - 2 years, 6 months, 18 days. Many friends and relatives, wife and children, accession to wealth or royal favour. In the first 18 months of this period very busy, seriously inclined to marry. In the latter 12 months, enemies increase through his own action, happiness, birth of children, acquisition of vehicles, happiness to relatives and family, enjoyments with prostitutes, showy, gains through trade, fraudulent schemes.", "level": "PD2"},
    "RahuKetu": {"name": "RahuKetuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Ketu - 1 year, 18 days. Danger, disease in the anus, no good and timely meals, epidemic diseases, danger of physical hurts and poison, ill-health to children, some swellings in the body, troubles through wife, danger from superiors, loss of wealth and honour, loss of children, death of cattle and misfortunes of all kinds.", "level": "PD2"},
    "RahuVenus": {"name": "RahuVenusPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Good", "body": "Neutral"}, "description": "Venus - 3 years. Accession to vehicles and things of foreign land, troubles from foes, relatives and diseases, acquisition of wealth and other advantages, friendly alliances, wife a source of fortune and happiness, benefits from superiors or heads above in office, liable to deception, false friends, gain in land, birth of a child or marriage.", "level": "PD2"},

    "JupiterSun": {"name": "JupiterSunPD2", "nature": "Neutral", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "The Sun's sub-period - 9 months, 18 days. Enemies, victory, ease, great diligence, coming in of wealth, royal favour and sound health, gain, good actions or fruits of good action, loss of bodily strength.", "level": "PD2"},
    "JupiterMoon": {"name": "JupiterMoonPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Good", "body": "Neutral"}, "description": "The Moon's sub-period - 1 year, 4 months. Increase of prosperity, gain of fame and fortune, acquisition or property, benefits through children, sexual intercourse with beautiful women, good meals and clothing, success and birth or a female child or marriage to some male member in the family, gain of money.", "level": "PD2"},
    "JupiterMars": {"name": "JupiterMarsPD2", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Mars' sub-period - 11 months, 6 days. Disappointments and troubles of various kinds, loss by thefts, loss of near and dear relatives, inflammatory disease, transfer or leave, failure in hopes and business, wandering, high fever, great risks, loss of wealth and depression of mind, pilgrimage to temples, acquisition of wealth and fame, adventures.", "level": "PD2"},
    "JupiterRahu": {"name": "JupiterRahuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Rahu's sub-period - 2 years, 4 months, 24 days. Income through low-caste people, apprehension of diseases, possibility of every possible calamity, deprivation of wealth.", "level": "PD2"},
    "JupiterJupiter": {"name": "JupiterJupiterPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Jupiter's sub-period - 2 years, 1 month, 18 days. Increase of property, domestic happiness, benefit from employment or occupation, birth of children, reputation, good meals, good deeds, health. royal favour, great diligence, success in all attempts, travels, dips in sacred rivers, pilgrimage, honour at stake if afflicted.", "level": "PD2"},
    "JupiterSaturn": {"name": "JupiterSaturnPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Saturn's sub-period - 2 years, 6 months, 12 days. A feeling of aversion, mental anguish, waste of wealth through sons, failure of business, increase of wealth and prosperity, pain in the body, rheumatic pains in limbs, trouble through wife or partners, failure in profit and credit, sorrows, fears, enmity of friends and relatives, adultery, unrighteous, a witness in court, quarrels in family, mental depression, funeral ceremonies for others.", "level": "PD2"},
    "JupiterMercury": {"name": "JupiterMercuryPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Mercury's sub-period - 2 years, 3 months, 6 days. Increase of wealth, good and auspicious works in the house, communion with relatives, happy, increase of knowledge, acquisition of wealth through trade, favour from rulers, material comforts, perfect practice of hospitality, gain through knowledge in fine arts, birth of a well-favoured child, advantages from superiors.", "level": "PD2"},
    "JupiterKetu": {"name": "JupiterKetuPD2", "nature": "Neutral", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Ketu's sub-period - 11 months, 6 days. Pilgrimages to holy shrines, increase of wealth, suffering for the sake of several seniors and rulers, death of partner if in business, change of residence, separation from relatives and friends, may forsake business, poisonous effects, loss of wealth, destruction of work, illness, boils.", "level": "PD2"},
    "JupiterVenus": {"name": "JupiterVenusPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Venus's sub-period - 2 years, 8 months. Appointment, wealth, reputation, gain of money, savings, development of sons and grandsons, jewels, good and delicious meals, marital happiness, auspicious works, reunion of the family, good success in profession or business, gain of land in the month of Taurus or Libra, much enjoyment, relatives, friends, peace or mind, acquisition or valuables, troubles from females and odium of public.", "level": "PD2"},

    "SaturnSun": {"name": "SaturnSunPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Bad", "body": "Bad"}, "description": "Sun - 11 months, 12 days. Loss of wife and children, trouble from rulers or robbers, sinking of heart, danger of blood poisoning, haemorrhage of the generative system, chronic poisoning, intestinal swellings, affliction of the eyes, sickness even to healthy children and wife, body full of pain and disorders, danger of death. fear of death to father-in-law.", "level": "PD2"},
    "SaturnMoon": {"name": "SaturnMoonPD2", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Moon - 1 year, 7 months. Increase in cattle, enmity of friends and relatives, cold affections, troubles and sickness, family disputes, loss of money and property, reduction to great need, mortgage of property and its recovery after a lapse of time, death of a near relative, sorrow, dislike of relatives, coming in of money, windy diseases.", "level": "PD2"},
    "SaturnMars": {"name": "SaturnMarsPD2", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Mars - 1 year, 1 month, 9 days. Some disgrace, serious enmity, strife, much blame, wanderings from place to place, unsettled life, many enemies, loss of money by fraud or theft, change of residence, serious illness, distress to brothers and friends, hot diseases.", "level": "PD2"},
    "SaturnRahu": {"name": "SaturnRahuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Rahu's sub-period - 2 years, 10 months, 6 days. Disease in every limb, loss of wealth by rulers, robbers and foes, danger of physical hurts, various physical troubles, fevers, enemies, increase of troubles.", "level": "PD2"},
    "SaturnJupiter": {"name": "SaturnJupiterPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Neutral", "love": "Neutral", "body": "Good"}, "description": "Jupiter - 2 years, 6 months, 12 days. Worship of gods and holy people, happiness to family, increase in bodily comforts, accomplishment of intentions by the help of superiors, increase of family circles, attainment of rank.", "level": "PD2"},
    "SaturnSaturn": {"name": "SaturnSaturnPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Saturn's sub-period 3 years, 3 days. Brings on diseases, troubles and torments, much mental anguish, rapacity of kings and free-hooters, loss of wealth, fear or poisonous effect to cattle, much sufferings to family, fever, wind or phlegm, bodily ailments and colic, body languishes, loss of money and children, serious enmities, dispute and troubles from relatives, blood and bilious complaints, quarrels in family, loss of money, mental derangement.", "level": "PD2"},
    "SaturnMercury": {"name": "SaturnMercuryPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Mercury's sub-period - 2 years, 8 months, 9 days. Charitable works, gain of wealth, birth of children, increase of knowledge in some branch, prosperity to children, success to relatives, general prosperity, favours and approbation from superiors, increase of happiness, wealth and fame, benefits occurring from acts of piety and customary religious observances, agriculture and commerce.", "level": "PD2"},
    "SaturnKetu": {"name": "SaturnKetuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Ketu's sub-period - 1 year, 1 month, 9 days. Rheumatism or sickness, danger of poison, danger from sons, loss of money, contentions and quarrels with vile and wicked people, dread of evil dreams, quarrels in family.", "level": "PD2"},
    "SaturnVenus": {"name": "SaturnVenusPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Good", "body": "Neutral"}, "description": "Venus - 3 years, 2 months. Auspicious, general happiness, attentions and favours from others, gifts, profits in business, increase of family members, victory over enemies, success in life, goodwill of relatives, accession to wife's property and wealth.", "level": "PD2"},

    "MercurySun": {"name": "MercurySunPD2", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Sun - 10 months, 6 days. Pains in head and stomach, enmity of people, loss of respect, danger of fire, anxieties, sickness to wife, troubles from enemies, many obstacles, troubles through superiors, acquisition of wealth.", "level": "PD2"},
    "MercuryMoon": {"name": "MercuryMoonPD2", "nature": "Neutral", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Good", "love": "Neutral", "body": "Bad"}, "description": "Moon - 1 year, 5 months. Loss of health, some swellings or hurts in the limbs, quarrels and troubles through women, many difficulties, gain of money through ladies and agriculture and trade, success, happiness, diseases, ill-will of enemies, miscarriage of every concern, risk from quadrupeds.", "level": "PD2"},
    "MercuryMars": {"name": "MercuryMarsPD2", "nature": "Neutral", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Bad"}, "description": "Mars sub-period - 11 months, 27 days. Disappearance of all dangers diseases or enemies, fame derived from acts of charity and beneficence, royal favour, danger from jaundice or bilious fever, affections of the blood, neuralgic pains and headaches, troubles through neighbors, sickness, wounds or hurts, quarrels, addiction to drinks, betting and prostitutes, boils and hurts of arms, travels in forests and villages, sorrows, royal disfavour, imprisonment.", "level": "PD2"},
    "MercuryRahu": {"name": "MercuryRahuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Good", "love": "Bad", "body": "Bad"}, "description": "Rahu - 2 years, 6 months, 18 days. Intercourse with servants and prostitutes, skin diseases, sufferings from hot diseases, bad company and dirty meals. change or present position, fear and danger through foreigners, disputes concerning property, failure in litigation, evil dreams. headaches, sickness and loss of appetite. wealth from friends and relatives, happiness, new earnings.", "level": "PD2"},
    "MercuryJupiter": {"name": "MercuryJupiterPD2", "nature": "Neutral", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Jupiter - 2 years, 3 months 6 days. Hatred of friends, relatives and elders, wealth, liable to diseases, acquisition of land and wealth, gain by trade, reputation, good happiness, good credit, benefits from superiors, birth of a child or marriage.", "level": "PD2"},
    "MercurySaturn": {"name": "MercurySaturnPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Saturn - 2 years, 8 months, 9 days. Bad luck. stranger to success and happiness, severe reversal, enmity, pain in the part governed by Saturn, downfall or disgrace to relatives, mind full of evil forebodings and distress. fear from diseases, loans, loss of children, destruction of family, scandals, troubles from foreigners, earnings through evil ways, acts of charity and beneficence, acquisition of wealth, material comforts through petty chiefs, failure in agricultural operations.", "level": "PD2"},
    "MercuryMercury": {"name": "MercuryMercuryPD2", "nature": "Good", "scores": {"mind": "Good", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Mercury's sub-period - 2 years, 4 months, 27 days. Acquisition of beautiful house and apparel, money through relatives, success in every undertaking, the birth of a brother or sister, increase in family, gain in business, good mind charitable acts, learning of mathematics and arts.", "level": "PD2"},
    "MercuryKetu": {"name": "MercuryKetuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Bad"}, "description": "Ketu - 11 months, 27 days. Sorrow, disease, loss of work and Dharma, bilious sickness, aimless wandering, loss of property, misfortune to relatives, troubles through doctors, mental anxiety, trouble from relatives, mental agony, loss of comfort, dread of enemy, failure in business.", "level": "PD2"},
    "MercuryVenus": {"name": "MercuryVenusPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Venus - 2 years, 10 months. Observance of duty, conformable to religion and morality, acquisition of wealth, clothes and jewels, birth or good children, happiness in married state, relatives prosper, trade increases, knowledge gained, return from a long journey, if not married, betrothal in this period, health, ornaments, vehicles, house, money gained.", "level": "PD2"},

    "KetuSun": {"name": "KetuSunPD2", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Bad", "body": "Bad"}, "description": "The Sun's sub-period - 4 months, 6 days. Disappointment, physical pain, exile in foreign country, peril and obstruction in every business, increase of knowledge, sickness in family, long journey and return, anxiety about wife's health.", "level": "PD2"},
    "KetuMoon": {"name": "KetuMoonPD2", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "The Moon's sub-period-7 months. Disputes about fair sex, trouble through children, gains and financial success, diseases of biliousness and cold, loss of relatives and money, destruction of wealth and distress of mind.", "level": "PD2"},
    "KetuMars": {"name": "KetuMarsPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Neutral", "body": "Bad"}, "description": "Mars' sub-period - 4 months, 27 days. Odium of sons, wife and younger brothers, loss of relatives, trouble from diseases, foes and bad rulers, path of progress obstructed, fear and anxiety, disputes and contests of different kinds, enemies arise, danger of disputes and destruction through females, sufferings from fever, fear of robbers, death, imprisonment, urinary diseases, loss and difficulties and surgical operations.", "level": "PD2"},
    "KetuRahu": {"name": "KetuRahuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Bad", "body": "Bad"}, "description": "Rahu - 1 year, 18 days. Loss of lands, imprisonment, quarrel with friends, danger of blood poisoning, danger of ruin, loss of property, fame and honour, fear of kings and robbers, sorrow, ruin of all business, adultery with mean women.", "level": "PD2"},
    "KetuJupiter": {"name": "KetuJupiterPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Good", "body": "Neutral"}, "description": "Jupiter - 11 months, 6 days. Exemption from ailments, acquisition of lands and birth of children, profitable transactions, association with people of good position, danger of poison, wife an object of pleasure, if unmarried marriage takes place.", "level": "PD2"},
    "KetuSaturn": {"name": "KetuSaturnPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Bad", "body": "Bad"}, "description": "Saturn - 1 year, 1 month, 9 days. Loss of wife, danger from enemies, imprisonment, loss of wealth, indigestion, property in danger or ruin, heavy loss in different ways, change of residence, some cutaneous diseases. anxiety owing to sickness of partner misgivings in the heart, mental anguish, difference of opinion with relations, exile in foreign countries.", "level": "PD2"},
    "KetuMercury": {"name": "KetuMercuryPD2", "nature": "Neutral", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Mercury - 11 months 27 days. Society of relatives, friends and the like, material gains from knowledge, danger from relatives, anxiety on account of children, failure in plans, deception, jealousy, falsehood, and knowledge.", "level": "PD2"},
    "KetuKetu": {"name": "KetuKetuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Ketu's sub-period - 4 months, 27 days. Fear of death of wife or children, loss of wealth and happiness, mental troubles, separation from relatives, subject to some estrangement, restraint or detention, danger of poison.", "level": "PD2"},
    "KetuVenus": {"name": "KetuVenusPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Bad", "money": "Neutral", "love": "Neutral", "body": "Bad"}, "description": "Venus - 1 year, 2 months. Wealth and happiness, birth of a child, efforts crowned with success, in the end sickness, wife ill, illness to children, quarrels, loss of relatives and friends, fever and dysentery.", "level": "PD2"},

    "VenusSun": {"name": "VenusSunPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Bad", "body": "Bad"}, "description": "Sun - 1 year. Anxious about everything, prosperity collapses, troubles with wife, children, land, family, disputes and quarrels, diseases affecting head, belly and eyes, damage in respect of agriculture.", "level": "PD2"},
    "VenusMoon": {"name": "VenusMoonPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Good", "money": "Neutral", "love": "Bad", "body": "Bad"}, "description": "Moon - 1 year, 8 months. Gains of females, education, knowledge, money, children and vehicles, worship of God, accomplishments of desires, troubles through wife, domestic happiness afterwards, pain and disease due to inflammation of nervous tissue and from lust and other passions of human nature.", "level": "PD2"},
    "VenusMars": {"name": "VenusMarsPD2", "nature": "Neutral", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Neutral", "love": "Neutral", "body": "Neutral"}, "description": "Mars - 1 year, 2 months. Flow of bile, disease of the eyes, great exertion, much income, acquisition or wealth, marriage, acquisition of lands, venereal diseases, danger from arms, exile in foreign places, atheistic tendencies, increase of property through the influence of females, negligence of duty, bent on pleasure and passion, temporary affection of eyes.", "level": "PD2"},
    "VenusRahu": {"name": "VenusRahuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Neutral", "body": "Neutral"}, "description": "Rahu - 3 years. Meditation, seclusion, quarrels among relatives and his people, entire change of surroundings, schemes of deception. miserliness, acquisition of lost property, dislike of relatives. evil from friends and injury by fire.", "level": "PD2"},
    "VenusJupiter": {"name": "VenusJupiterPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Jupiter - 2 years, 8 months. Means of livelihood settled, gains from profession, benefits through superiors or employers or persons ruled by Jupiter fame, anxiety, quarrels with saints and religious men, gain of knowledge, end of dependence, worship of certain inferior natural forces, happiness and health, marriages, sexual intercourse, increase of family reputation and good deeds, wealth. ultimate happiness, wife and children suffer in the end.", "level": "PD2"},
    "VenusSaturn": {"name": "VenusSaturnPD2", "nature": "Bad", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Neutral", "money": "Bad", "love": "Bad", "body": "Bad"}, "description": "Saturn - 3 years, 2 months Sexual intercourse with females advanced in age, accession to lands and wealth, disappearance of enemies, affection of excretory system, piles, etc., rheumatic pains in legs and hands, danger to eye sight, distaste for food, loss of appetite, physical condition poor, loss of money, wanderings, servitude, bolting and gambling, addiction to liquor, bad company, etc., ill-health, loss of memory, impotence.", "level": "PD2"},
    "VenusMercury": {"name": "VenusMercuryPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Good", "family": "Good", "money": "Good", "love": "Good", "body": "Neutral"}, "description": "Mercury - 2 years, 10 months. Association with prostitutes, enjoyments, knowledge, mathematical learning, success in litigations, inclination to learn music, piles and other hot ailments, pleasure through wife and children, increase of wealth, gain of knowledge in arts and sciences, wealth, royal favour, prosperity on a large scale and sound health.", "level": "PD2"},
    "VenusKetu": {"name": "VenusKetuPD2", "nature": "Bad", "scores": {"mind": "Bad", "studies": "Neutral", "family": "Bad", "money": "Bad", "love": "Bad", "body": "Bad"}, "description": "Ketu - 1 year, 2 months. Discordance, death of relatives, injury inflicted by enemies, misgivings in heart, deprivation of wealth, troubles through wife, danger from quadrupeds, illness to partner or a member of the family, accidental blood poisoning, delirious fits, weakness in body and mind, gradual loss of wealth, loss of relatives, bad company, abode in seclusion, manifold sorrows, but happiness in the end.", "level": "PD2"},
    "VenusVenus": {"name": "VenusVenusPD2", "nature": "Good", "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Good", "love": "Neutral", "body": "Neutral"}, "description": "Venus - 3 years, 4 months. Success, good servants and good many pleasures, money plentiful. disappearance of enemies, attainment of fame and birth of children.", "level": "PD2"},
}

# ---------------------------------------------------------------------------
# PD3 – 81 entries  (9 maha lords × 9 antardasa lords)
# All descriptions are empty in the source; only scores are preserved.
# Key: "<MahaLord><AntarLord>"
# ---------------------------------------------------------------------------

_PD3_LORDS = ["Sun", "Moon", "Mars", "Rahu", "Jupiter", "Saturn", "Mercury", "Ketu", "Venus"]

PD3_DATA: Dict[str, dict] = {}
for _maha in _PD3_LORDS:
    for _antar in _PD3_LORDS:
        _key = f"{_maha}{_antar}"
        PD3_DATA[_key] = {
            "name": f"{_maha}{_antar}PD3",
            "nature": "Empty",
            "scores": {"mind": "Neutral", "studies": "Neutral", "family": "Good", "money": "Bad", "love": "Neutral", "body": "Neutral"},
            "description": "",
            "level": "PD3",
        }


# ---------------------------------------------------------------------------
# Public accessor functions
# ---------------------------------------------------------------------------

def get_pd1_interpretation(planet: str, sign: str) -> Optional[dict]:
    """
    Return the PD1 (maha dasa) interpretation for the given planet
    placed in the given sign at birth.

    Args:
        planet: Planet name (e.g. "Sun", "Moon", "Mars", "Mercury",
                 "Jupiter", "Venus", "Saturn", "Rahu", "Ketu")
        sign:   Zodiac sign name (e.g. "Aries", "Taurus", ..., "Pisces")

    Returns:
        Interpretation dict or None if not found.
    """
    key = f"{sign}{planet}"
    return PD1_DATA.get(key)


def get_pd2_interpretation(maha_lord: str, bhukti_lord: str) -> Optional[dict]:
    """
    Return the PD2 (antardasa / bhukti) interpretation.

    Args:
        maha_lord:   Maha dasa lord (e.g. "Sun")
        bhukti_lord: Bhukti lord (e.g. "Moon")

    Returns:
        Interpretation dict or None if not found.
    """
    key = f"{maha_lord}{bhukti_lord}"
    return PD2_DATA.get(key)


def get_pd3_interpretation(maha_lord: str, antar_lord: str) -> Optional[dict]:
    """
    Return the PD3 (pratyantardasa) scores (descriptions are empty).

    Args:
        maha_lord:  Maha dasa lord
        antar_lord: Antardasa lord

    Returns:
        Interpretation dict or None if not found.
    """
    key = f"{maha_lord}{antar_lord}"
    return PD3_DATA.get(key)


def get_dasa_interpretations_for_schedule(
    schedule: dict,
    birth_planet_signs: dict,
) -> dict:
    """
    Attach PD1 / PD2 interpretations to an existing Vimshottari dasa schedule.

    Args:
        schedule:
            Output of ``get_vimshottari_dasa_schedule()``.  Expected shape::

                {
                    "maha_dasas": [
                        {
                            "maha_lord": "Sun",
                            "bhuktis": [
                                {"bhukti_lord": "Sun", ...},
                                ...
                            ],
                            ...
                        },
                        ...
                    ],
                    ...
                }

        birth_planet_signs:
            A mapping of planet name → natal sign, e.g.::

                {"Sun": "Aries", "Moon": "Cancer", "Mars": "Scorpio", ...}

    Returns:
        The *same* schedule dict with ``pd1_interpretation`` added to each
        maha dasa entry and ``pd2_interpretation`` added to each bhukti entry.
    """
    for maha in schedule.get("maha_dasas", []):
        lord = maha.get("maha_lord", "")
        natal_sign = birth_planet_signs.get(lord)
        maha["pd1_interpretation"] = get_pd1_interpretation(lord, natal_sign) if natal_sign else None

        for bhukti in maha.get("bhuktis", []):
            b_lord = bhukti.get("bhukti_lord", "")
            bhukti["pd2_interpretation"] = get_pd2_interpretation(lord, b_lord)

    return schedule
